# Generated by Django 3.2.3 on 2021-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_rename_image_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
